SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio * 1.05 FROM producto;
SELECT nombre, format(precio, 2) AS "Precio €", format(precio * 1.05, 2) AS "Precio USS" FROM producto;
SELECT upper(nombre), precio FROM producto;
SELECT lower(nombre), precio FROM producto;
SELECT nombre, concat ( upper(substring(nombre, 1, 2)), substring(nombre, 3) ) FROM fabricante;
SELECT nombre, round(precio) FROM producto;
SELECT nombre, TRUNCATE(precio, 0) FROM producto;
SELECT p.nombre, f.codigo AS "codigo fabricante" FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT f.codigo AS "codigo fabricante", count(*) FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo group BY f.codigo;
SELECT nombre FROM fabricante ORDER BY nombre ASC;
SELECT nombre FROM fabricante ORDER BY nombre DESC;
SELECT * FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 3, 3;
SELECT producto.nombre AS product, producto.precio AS precio FROM tienda.producto ORDER BY precio ASC LIMIT 1;
SELECT producto.nombre AS product, producto.precio AS precio FROM tienda.producto ORDER BY precio DESC LIMIT 1;
SELECT p.nombre AS producto, f.codigo AS "codigo fabricante" FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.codigo = 2;
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante ORDER BY fabricante ASC;
SELECT p.codigo AS "codigo producto", p.nombre AS producto, f.codigo AS "codigo fabricante", f.nombre AS "fabricante" FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante;
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE precio =( SELECT min(p.precio) FROM tienda.producto p );
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE precio =( SELECT max(p.precio) FROM tienda.producto p );
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = "lenovo";
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = "crucial" AND p.precio > 200;
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Asus' OR f.nombre = "Hewlett-Packard" OR f.nombre = 'Seagate';
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre in ('Asus', 'Hewlett-Packard', 'Seagate');
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre LIKE "%e";
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre regexp "w";
SELECT p.nombre AS producto, p.precio AS precio, f.nombre AS fabricante FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE precio >= 180 ORDER BY precio DESC, producto ASC;
SELECT f.codigo, f.nombre AS fabricante FROM tienda.fabricante f JOIN producto p ON p.codigo_fabricante = f.codigo group BY f.codigo;
SELECT f.codigo, f.nombre AS fabricante, p.nombre AS producto FROM tienda.fabricante f LEFT JOIN producto p ON p.codigo_fabricante = f.codigo;
SELECT f.codigo, f.nombre AS fabricante, p.nombre AS producto FROM tienda.fabricante f LEFT JOIN producto p ON p.codigo_fabricante = f.codigo WHERE producto;
SELECT nombre AS produto FROM tienda.producto WHERE codigo_fabricante =( SELECT codigo FROM fabricante WHERE nombre = "lenovo" );
SELECT p.nombre AS produto, precio AS precio FROM tienda.producto p WHERE precio = ( SELECT max(precio) FROM producto WHERE codigo_fabricante = ( SELECT codigo FROM fabricante WHERE nombre = "lenovo" ) ) AND codigo_fabricante <> ( SELECT codigo FROM fabricante WHERE nombre = "lenovo" );
SELECT p.nombre, p.precio, f.nombre FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = "lenovo" ORDER BY precio DESC LIMIT 1;
SELECT p.nombre, p.precio, f.nombre FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'Hewlett-Packard' ORDER BY precio ASC LIMIT 1;
SELECT p.nombre AS produto, precio AS precio FROM tienda.producto p WHERE precio >= ( SELECT max(precio) FROM producto WHERE codigo_fabricante = ( SELECT codigo FROM fabricante WHERE nombre = "lenovo" ) ) AND codigo_fabricante <> ( SELECT codigo FROM fabricante WHERE nombre = "lenovo" );
SELECT p.nombre, p.precio, f.nombre FROM tienda.producto p JOIN fabricante f ON f.codigo = p.codigo_fabricante WHERE f.nombre = 'asus' AND p.precio > ( SELECT avg(p.precio) FROM tienda.producto p );
